[title.actions]
Enter = "Confirm"
Escape = "Cancel"

[playing.play_keys]
S = "Key1"
D = "Key2"
F = "Key3"
J = "Key4"
K = "Key5"
L = "Key6"
ShiftLeft = "Key7"

[playing.scratch_up_keys]
Space = "ScratchUp"

[playing.scratch_down_keys]
ShiftRight = "ScratchDown"

[result.actions]
Enter = "Confirm"
Escape = "Cancel"
