[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23", features = ["derive"] }
egui = "0.36.2"
egui-wgpu = { version = "0.36.2", default-features = false }
egui-winit = "0.36.2"
pollster = "1.0.1"
wgpu = { version = "30.0.1", default-features = false, features = ["gles", "wgsl"] }
winit = "0.30.13"
log.workspace = true