[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
winit.workspace = true

env_logger = "0.11.11"

loop_manager = { path = "../loop_manager" }
play_core = { path = "../play_core" }
debug_window = { path = "../debug_window" }
main_window = { path = "../main_window" }
