[package]
name = "debug_window"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.36.2"
egui-wgpu = { version = "0.36.2", default-features = false }
egui-winit = "0.36.2"
wgpu = { version = "30.0.1", default-features = false, features = ["gles", "wgsl"] }
winit = "0.30.13"

log.workspace = true
pollster.workspace = true

play_core = { path = "../play_core" }
loop_manager = { path = "../loop_manager" }